export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export interface Chapter {
  /** 1-based chapter number */
  number: number;
  /** Alias for number — kept for back-compat */
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  difficulty: Difficulty;
  estimatedMinutes: number;
  phase: 1 | 2 | 3;
  topics: string[];
  conceptCount: number;
  /** Key of the matching interactive visualization, if one exists */
  visualization?: string;
}

export const chapters: Chapter[] = [
  // ── Phase 1: Foundation (Ch 1-5) ─────────────────────────────────────────
  {
    number: 1,
    id: 1,
    slug: 'what-is-nodejs',
    title: 'Node.js Kya Hai?',
    subtitle: 'V8 engine, runtime, aur JavaScript ka server-side safar',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    phase: 1,
    topics: ['V8 Engine', 'Runtime Environment', 'JS History', 'Node vs Browser'],
    conceptCount: 6,
    visualization: 'architecture',
  },
  {
    number: 2,
    id: 2,
    slug: 'event-loop-deep-dive',
    title: 'Event Loop — Node ka Dil',
    subtitle: 'Single thread mein concurrent magic kaise hota hai',
    difficulty: 'beginner',
    estimatedMinutes: 45,
    phase: 1,
    topics: ['Call Stack', 'Web APIs', 'Callback Queue', 'Microtasks', 'Phases'],
    conceptCount: 8,
    visualization: 'event-loop',
  },
  {
    number: 3,
    id: 3,
    slug: 'modules-commonjs-esm',
    title: 'Modules: CJS vs ESM',
    subtitle: 'require() se import tak — module system ka poora sach',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    phase: 1,
    topics: ['CommonJS', 'ES Modules', 'exports', 'import/export', 'Circular Deps'],
    conceptCount: 7,
    visualization: 'module-resolution',
  },
  {
    number: 4,
    id: 4,
    slug: 'npm-and-packages',
    title: 'NPM & Package Management',
    subtitle: 'Dependencies, versioning, scripts — sab kuch',
    difficulty: 'beginner',
    estimatedMinutes: 20,
    phase: 1,
    topics: ['package.json', 'Semver', 'npm scripts', 'npx', 'lock files'],
    conceptCount: 5,
  },
  {
    number: 5,
    id: 5,
    slug: 'file-system',
    title: 'File System API',
    subtitle: 'fs module se files padhna, likhna, manage karna',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    phase: 1,
    topics: ['fs.readFile', 'fs.writeFile', 'Promises API', 'Streams', 'Path module'],
    conceptCount: 7,
  },

  // ── Phase 2: Core Skills (Ch 6-13) ───────────────────────────────────────
  {
    number: 6,
    id: 6,
    slug: 'async-callbacks',
    title: 'Async: Callbacks & Error Handling',
    subtitle: 'Callback hell se baahaar aao — error-first pattern',
    difficulty: 'intermediate',
    estimatedMinutes: 40,
    phase: 2,
    topics: ['Error-First Callbacks', 'Callback Hell', 'Pyramid of Doom', 'Best Practices'],
    conceptCount: 6,
  },
  {
    number: 7,
    id: 7,
    slug: 'promises',
    title: 'Promises — Async Ka Naya Tarika',
    subtitle: 'Promise chaining, .then(), .catch(), Promise.all()',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    phase: 2,
    topics: ['Promise States', 'Chaining', 'Promise.all', 'Promise.race', 'Promise.allSettled'],
    conceptCount: 8,
  },
  {
    number: 8,
    id: 8,
    slug: 'async-await',
    title: 'Async/Await — Modern Async',
    subtitle: 'Promises ko synchronous-style mein likhna',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    phase: 2,
    topics: ['async functions', 'await keyword', 'try/catch', 'Parallel Execution', 'Top-level await'],
    conceptCount: 6,
  },
  {
    number: 9,
    id: 9,
    slug: 'streams',
    title: 'Streams — Data Flow Mastery',
    subtitle: 'GB data ko bina memory exhaust kiye handle karo',
    difficulty: 'intermediate',
    estimatedMinutes: 55,
    phase: 2,
    topics: ['Readable', 'Writable', 'Transform', 'Piping', 'Backpressure'],
    conceptCount: 9,
    visualization: 'streams',
  },
  {
    number: 10,
    id: 10,
    slug: 'buffers-and-binary',
    title: 'Buffers & Binary Data',
    subtitle: 'Raw bytes handle karna — images, files, network data',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    phase: 2,
    topics: ['Buffer API', 'Encodings', 'TypedArrays', 'Binary Protocols'],
    conceptCount: 5,
  },
  {
    number: 11,
    id: 11,
    slug: 'http-and-rest-apis',
    title: 'HTTP Module & REST APIs',
    subtitle: 'Scratch se HTTP server banana, routing, middleware',
    difficulty: 'intermediate',
    estimatedMinutes: 60,
    phase: 2,
    topics: ['HTTP module', 'Express.js', 'Routing', 'Middleware', 'REST conventions'],
    conceptCount: 10,
    visualization: 'http',
  },
  {
    number: 12,
    id: 12,
    slug: 'express-deep-dive',
    title: 'Express.js Deep Dive',
    subtitle: 'Production-grade Express patterns aur best practices',
    difficulty: 'intermediate',
    estimatedMinutes: 70,
    phase: 2,
    topics: ['Router', 'Error Middleware', 'Body Parsing', 'CORS', 'Rate Limiting'],
    conceptCount: 11,
  },
  {
    number: 13,
    id: 13,
    slug: 'databases-and-orms',
    title: 'Databases & ORMs',
    subtitle: 'PostgreSQL, MongoDB, Prisma — sahi choice karo',
    difficulty: 'intermediate',
    estimatedMinutes: 65,
    phase: 2,
    topics: ['PostgreSQL', 'MongoDB', 'Prisma', 'Mongoose', 'Connection Pooling'],
    conceptCount: 10,
    visualization: 'n-plus-one',
  },

  // ── Phase 3: Expert Level (Ch 14-23) ─────────────────────────────────────
  {
    number: 14,
    id: 14,
    slug: 'authentication-jwt',
    title: 'Authentication & JWT',
    subtitle: 'Secure auth system — JWT, sessions, refresh tokens',
    difficulty: 'advanced',
    estimatedMinutes: 75,
    phase: 3,
    topics: ['JWT', 'Sessions', 'OAuth 2.0', 'Refresh Tokens', 'Security Headers'],
    conceptCount: 9,
    visualization: 'jwt-auth',
  },
  {
    number: 15,
    id: 15,
    slug: 'caching-redis',
    title: 'Caching with Redis',
    subtitle: 'Application ko 10x fast karo smart caching se',
    difficulty: 'advanced',
    estimatedMinutes: 50,
    phase: 3,
    topics: ['Redis Data Structures', 'Cache Strategies', 'TTL', 'Cache Invalidation', 'Bull Queues'],
    conceptCount: 8,
  },
  {
    number: 16,
    id: 16,
    slug: 'websockets-realtime',
    title: 'WebSockets & Real-time',
    subtitle: 'Socket.IO se live features banana — chat, notifications',
    difficulty: 'advanced',
    estimatedMinutes: 60,
    phase: 3,
    topics: ['WebSocket Protocol', 'Socket.IO', 'Rooms & Namespaces', 'Scaling WS', 'SSE'],
    conceptCount: 8,
  },
  {
    number: 17,
    id: 17,
    slug: 'worker-threads',
    title: 'Worker Threads & Clustering',
    subtitle: 'CPU-intensive tasks ke liye true parallelism',
    difficulty: 'advanced',
    estimatedMinutes: 55,
    phase: 3,
    topics: ['Worker Threads', 'Cluster Module', 'SharedArrayBuffer', 'Message Passing', 'PM2'],
    conceptCount: 7,
    visualization: 'cluster-workers',
  },
  {
    number: 18,
    id: 18,
    slug: 'testing',
    title: 'Testing Node.js Apps',
    subtitle: 'Unit, integration, e2e — confidence ke saath ship karo',
    difficulty: 'advanced',
    estimatedMinutes: 65,
    phase: 3,
    topics: ['Jest', 'Supertest', 'Mocking', 'Coverage', 'TDD'],
    conceptCount: 8,
  },
  {
    number: 19,
    id: 19,
    slug: 'performance-profiling',
    title: 'Performance & Profiling',
    subtitle: 'Bottlenecks dhundho aur fix karo — memory leaks tak',
    difficulty: 'advanced',
    estimatedMinutes: 60,
    phase: 3,
    topics: ['Node Inspector', 'Flame Graphs', 'Memory Profiling', 'Clinic.js', 'Load Testing'],
    conceptCount: 8,
  },
  {
    number: 20,
    id: 20,
    slug: 'security',
    title: 'Security Best Practices',
    subtitle: 'OWASP se production-safe apps banana',
    difficulty: 'advanced',
    estimatedMinutes: 55,
    phase: 3,
    topics: ['SQL Injection', 'XSS', 'CSRF', 'Helmet.js', 'Input Validation'],
    conceptCount: 9,
  },
  {
    number: 21,
    id: 21,
    slug: 'microservices',
    title: 'Microservices Architecture',
    subtitle: 'Monolith se microservices tak — kab aur kaise',
    difficulty: 'advanced',
    estimatedMinutes: 80,
    phase: 3,
    topics: ['Service Communication', 'gRPC', 'Message Queues', 'API Gateway', 'Service Discovery'],
    conceptCount: 10,
    visualization: 'microservices',
  },
  {
    number: 22,
    id: 22,
    slug: 'docker-and-containers',
    title: 'Docker & Containers',
    subtitle: 'Node apps ko containerize karo — dev se prod tak',
    difficulty: 'advanced',
    estimatedMinutes: 70,
    phase: 3,
    topics: ['Dockerfile', 'Docker Compose', 'Multi-stage Builds', 'Health Checks', 'Networking'],
    conceptCount: 8,
  },
  {
    number: 23,
    id: 23,
    slug: 'deployment-and-ci-cd',
    title: 'Deployment & CI/CD',
    subtitle: 'AWS/GCP pe deploy karo — zero-downtime, auto-scale',
    difficulty: 'advanced',
    estimatedMinutes: 75,
    phase: 3,
    topics: ['GitHub Actions', 'AWS EC2/ECS', 'Nginx', 'SSL/TLS', 'Blue-Green Deploy'],
    conceptCount: 9,
  },
];

export const phases = [
  {
    number: 1 as const,
    name: 'Foundation',
    description: 'Node.js ki basics — engine se event loop tak',
    color: '#10B981',
    textColor: 'text-[#10B981]',
    bgColor: 'bg-[#10B981]',
    borderColor: 'border-[#10B981]',
    chapters: chapters.filter((c) => c.phase === 1),
  },
  {
    number: 2 as const,
    name: 'Core Skills',
    description: 'Async mastery, streams, aur production APIs',
    color: '#F59E0B',
    textColor: 'text-[#F59E0B]',
    bgColor: 'bg-[#F59E0B]',
    borderColor: 'border-[#F59E0B]',
    chapters: chapters.filter((c) => c.phase === 2),
  },
  {
    number: 3 as const,
    name: 'Expert Level',
    description: 'Performance, scaling, security, deployment',
    color: '#7C3AED',
    textColor: 'text-[#7C3AED]',
    bgColor: 'bg-[#7C3AED]',
    borderColor: 'border-[#7C3AED]',
    chapters: chapters.filter((c) => c.phase === 3),
  },
];

export const difficultyConfig: Record<
  Difficulty,
  { label: string; color: string; bg: string; border: string }
> = {
  beginner: {
    label: 'Beginner',
    color: 'text-[#10B981]',
    bg: 'bg-[rgba(16,185,129,0.12)]',
    border: 'border-[rgba(16,185,129,0.3)]',
  },
  intermediate: {
    label: 'Intermediate',
    color: 'text-[#F59E0B]',
    bg: 'bg-[rgba(245,158,11,0.12)]',
    border: 'border-[rgba(245,158,11,0.3)]',
  },
  advanced: {
    label: 'Advanced',
    color: 'text-[#7C3AED]',
    bg: 'bg-[rgba(124,58,237,0.12)]',
    border: 'border-[rgba(124,58,237,0.3)]',
  },
};
